### ISSUE TITLE
Google Analitycs V4

### ISSUE THREAD

**Issue by nlbi21** [based-ghost/react-seo-friendly-spa-template#1]
Hey guys react-ga is not compatible with Google Analytics 4

https://github.com/react-ga/react-ga/issues/460

Is there any other solution or alternative while they support it?

thanks!

**Comment by based-ghost** [comment]
@nlbi21 - Hey, thanks for the heads-up - I wasn't aware of this issue. I'll have to take a look around to see if there is a package that offers an alternative, otherwise the fallback option would be to roll my own solution (simplified, less customizable).

**Comment by based-ghost** [comment]
This looks to be addressed in latest version of react-ga package.
