### ISSUE TITLE
Feature Request: Toggle Theme

### ISSUE THREAD

**Issue by OGoodness** [based-ghost/react-seo-friendly-spa-template#3]
I really like your "Toggle Theme" on your website: https://www.basedghostdevelopment.com/

Was hoping you could implement that as a standard feature, or something. I'm having trouble replicating your results.

**Comment by based-ghost** [comment]
@OGoodness - Ya, I believe I can add that without too much work. The `ThemeToggle` component featured on that site is built using `Vue`'s new composition API which very closely follows `React Hooks` API (so the translation into React code should be smooth).

**Comment by OGoodness** [comment]
That'd be great! I'll be sure to look out for an update on the Vue version :D

**Comment by OGoodness** [comment]
Have you gotten the chance to implement this?

**Comment by based-ghost** [comment]
@OGoodness - Sorry for the very late response. If you still need that "Toggle Theme" functionality, I have added that to the code base. You can check out the embedded demo gif in the README.md to get a an idea of how it looks in this application.

**Comment by based-ghost** [comment]
Added functionality.
